version: '3'
services:
  email-summarizer-app:
    build: .
    image: email-summarizer:latest
    ports:
      - 8501:8501
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
